const envconfig = {
  INFURA_KEY: process.env.NEXT_PUBLIC_INFURA_KEY || process.env.INFURA_KEY || "",
  MAINNET_COIN_ADDRESS: process.env.NEXT_PUBLIC_MAINNET_COIN_ADDRESS || process.env.MAINNET_COIN_ADDRESS || "",
  RINKEBY_COIN_ADDRESS: process.env.NEXT_PUBLIC_RINKEBY_COIN_ADDRESS || process.env.RINKEBY_COIN_ADDRESS || "",
  MAINNET_STAKING_ADDRESS: process.env.NEXT_PUBLIC_MAINNET_STAKING_ADDRESS || process.env.MAINNET_STAKING_ADDRESS || "",
  RINKEBY_STAKING_ADDRESS: process.env.NEXT_PUBLIC_RINKEBY_STAKING_ADDRESS || process.env.RINKEBY_STAKING_ADDRESS || "",
  MAINNET_PLAYABLES_ADDRESS:
    process.env.NEXT_PUBLIC_MAINNET_PLAYABLES_ADDRESS || process.env.MAINNET_PLAYABLES_ADDRESS || "",
  RINKEBY_PLAYABLES_ADDRESS:
    process.env.NEXT_PUBLIC_RINKEBY_PLAYABLES_ADDRESS || process.env.RINKEBY_PLAYABLES_ADDRESS || "",
  DEFAULT_NETWORK: process.env.NEXT_PUBLIC_DEFAULT_NETWORK || process.env.DEFAULT_NETWORK || 1,
};

export default envconfig;
