/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPromoter, IPromoterInterface } from "../IPromoter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "promoter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "ethRevenue",
        type: "uint256",
      },
    ],
    name: "addRevenue",
    outputs: [
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "code",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "ethRevenue",
        type: "uint256",
      },
    ],
    name: "addRevenueByCode",
    outputs: [
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPromoter__factory {
  static readonly abi = _abi;
  static createInterface(): IPromoterInterface {
    return new utils.Interface(_abi) as IPromoterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPromoter {
    return new Contract(address, _abi, signerOrProvider) as IPromoter;
  }
}
