/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IAffiliateInterface extends utils.Interface {
  contractName: "IAffiliate";
  functions: {
    "payoff(address)": FunctionFragment;
    "reward(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "payoff", values: [string]): string;
  encodeFunctionData(functionFragment: "reward", values: [string]): string;

  decodeFunctionResult(functionFragment: "payoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reward", data: BytesLike): Result;

  events: {};
}

export interface IAffiliate extends BaseContract {
  contractName: "IAffiliate";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAffiliateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    payoff(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { eth: BigNumber; bhc: BigNumber }>;

    reward(
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  payoff(
    addr: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { eth: BigNumber; bhc: BigNumber }>;

  reward(
    code: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    payoff(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { eth: BigNumber; bhc: BigNumber }>;

    reward(code: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    payoff(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    reward(
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    payoff(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reward(
      code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
